apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        name: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/akmalm007/karsajobs-ui:latest
          ports:
            - containerPort: 8000
          env:
            - name: VUE_APP_BACKEND
              value:
