apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs
  name: karsajobs
spec:
  ports:
    - ports: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: karsajobs
  type: NodePort
