# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipping
  name: shipping
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: shipping
  type: NodePort
