apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mongo
  labels: 
    app: mongo 
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo
  template: 
    metadata:
      labels:
        app: mongo
        tier: backend 
    spec: 
      containers:
        - image: mongo:4.4.3
          name: mongo 
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-crednetials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017  
              name: mongo 
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-config-map 
              mountPath: /config
            - name: mongo-credentials 
              mountPath: /etc/mongo-credentials 
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim: 
            claimName: mongo-pv-claim 
        - name: mongo-config-map
          configMap: 
            name: mongo-conf
            items: 
              - key: mongo.conf 
                path: mongo.conf 
        - name: mongo-credentials 
          secret:
            secretName: mongo-credentials
